name: Deploy LIMBO-Style Game

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      
      - name: Build LIMBO Game
        run: |
          mkdir -p dist
          cp web/index.html dist/
          cp web/limbo3d.js dist/
          cp web/dimbo-spider-logo.jpg dist/
          cp web/settings.json dist/
          echo "🎮 LIMBO-style game built"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4