name: Deploy DIMBO to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build LIMBO 3D Game  
        run: |
          mkdir -p dist
          echo "🎮 Building LIMBO 3D/4D JavaScript Engine..."
          
          # Copy ONLY the JavaScript version - NO WASM
          cp web/index.html dist/
          cp web/game.js dist/
          cp web/limbo3d.js dist/
          cp web/dimbo-spider-logo.jpg dist/
          cp web/settings.json dist/
          
          echo "✅ LIMBO 3D/4D Game built successfully!"
          echo "📦 JavaScript-only build (no WASM confusion):"
          ls -la dist/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist
          
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4